trigger:
- main
  
pool:
  vmImage: ubuntu-latest
  
variables:
  buildConfiguration: 'Release'
  
steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.400'
    
- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new'
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: Install EF tools
  inputs:
    command: custom
    custom: 'tool'
    arguments: install dotnet-ef

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
    publishTestResults: true
    projects: '**/*Tests/*.csproj'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: Create SQL Scripts
  inputs:
    command: custom
    custom: 'ef '
    arguments: migrations script --output $(Build.SourcesDirectory)/SQL/migration.sql --idempotent --project $(Build.SourcesDirectory)/CandidateJourney.Infrastructure/CandidateJourney.Infrastructure.csproj --context CandidateJourneyDbContext

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/CandidateJourney.API.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Migration script'
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/SQL/migration.sql
    ArtifactName: MigrationScript